radius_prepod:
    resource: "@RadiusPrepodBundle/Resources/config/routing.yml"
    type: rest
    prefix:   /api/{version}

app:
    resource: '@AppBundle/Controller/'
    type: annotation

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
